// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eejnkddyhrxzaunlksag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVlam5rZGR5aHJ4emF1bmxrc2FnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc5NDk4NzgsImV4cCI6MjA4MzUyNTg3OH0.LIZ5miVirexM8tzvtFGZQ-HSOKsPRweQ5YjTq1X3euw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});